name: Development Build
on: push

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
      - name: Build
        run: ./gradlew build
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: "latest-dev-build-1.12.2"
          prerelease: true
          title: "Dev build 1.12.2 Build"
          files: |
            ./build/libs/*.jar
